language: php

php:
  - 7.0.4

before_install:
  - composer self-update
  - php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"
  - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=ldap.so" >> test.ini

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -c test.ini tests
