sudo: required
language: php

php:
  - 7.1

before_install:
  - echo "extension=zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "zend_extension=xdebug.so" >> test.ini
  - echo "xdebug.remote_enable=on" >> test.ini
  - echo "xdebug.remote_host=127.0.0.1" >> test.ini
  - echo "xdebug.remote_port=9000" >> test.ini
  - echo "xdebug.remote_handler=dbgp" >> test.ini

install:
  - sudo apt-get update -qq
  # Install ZeroMQ
  - sudo apt-get install -y libzmq3-dev libzmq3
  # Install php binding of ZeroMQ
  - yes '' | pecl install channel://pecl.php.net/zmq-1.1.3
  - composer install --no-interaction --prefer-source
  - travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar

script:
  - ./vendor/bin/tester -j 4 -c test.ini tests --coverage ./coverage.xml --coverage-src ./app
  - ./phpstan/run.php analyse -l 4 -c phpstan/phpstan.neon app

after_script:
  - php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true
