language: php

php:
  - 7.0.4

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y php-codesniffer
  - composer self-update
  - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester tests 

after_script:
  - phpcs app
