language: php

php:
  - 7.0.4

before_install:
  - composer self-update
  - echo "extension=ldap.so" >> test.ini

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -c test.ini tests
