language: php

php:
  - 7.0.4

before_install:
  - composer self-update
  - echo "extension=ldap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester tests
