<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260717180905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assignment CHANGE id id CHAR(36) NOT NULL, CHANGE exercise_config_id exercise_config_id CHAR(36) DEFAULT NULL, CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL, CHANGE group_id group_id CHAR(36) DEFAULT NULL, CHANGE is_public is_public TINYINT NOT NULL, CHANGE is_bonus is_bonus TINYINT NOT NULL, CHANGE allow_second_deadline allow_second_deadline TINYINT NOT NULL, CHANGE can_view_limit_ratios can_view_limit_ratios TINYINT NOT NULL, CHANGE visible_from visible_from DATETIME DEFAULT NULL, CHANGE can_view_judge_stdout can_view_judge_stdout TINYINT NOT NULL, CHANGE score_config_id score_config_id CHAR(36) DEFAULT NULL, CHANGE can_view_judge_stderr can_view_judge_stderr TINYINT NOT NULL, CHANGE merge_judge_logs merge_judge_logs TINYINT NOT NULL, CHANGE plagiarism_batch_id plagiarism_batch_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE assignment_localized_assignment CHANGE assignment_id assignment_id CHAR(36) NOT NULL, CHANGE localized_assignment_id localized_assignment_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_disabled_runtime_environments CHANGE assignment_id assignment_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_localized_exercise CHANGE assignment_id assignment_id CHAR(36) NOT NULL, CHANGE localized_exercise_id localized_exercise_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_runtime_environment CHANGE assignment_id assignment_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_hardware_group CHANGE assignment_id assignment_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_exercise_limits CHANGE assignment_id assignment_id CHAR(36) NOT NULL, CHANGE exercise_limits_id exercise_limits_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_exercise_environment_config CHANGE assignment_id assignment_id CHAR(36) NOT NULL, CHANGE exercise_environment_config_id exercise_environment_config_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_exercise_test CHANGE assignment_id assignment_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_exercise_file CHANGE assignment_id assignment_id CHAR(36) NOT NULL, CHANGE exercise_file_id exercise_file_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_attachment_file CHANGE assignment_id assignment_id CHAR(36) NOT NULL, CHANGE attachment_file_id attachment_file_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE assignment_solution CHANGE id id CHAR(36) NOT NULL, CHANGE assignment_id assignment_id CHAR(36) DEFAULT NULL, CHANGE solution_id solution_id CHAR(36) DEFAULT NULL, CHANGE accepted accepted TINYINT NOT NULL, CHANGE last_submission_id last_submission_id CHAR(36) DEFAULT NULL, CHANGE plagiarism_batch_id plagiarism_batch_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE assignment_solution_submission CHANGE id id CHAR(36) NOT NULL, CHANGE assignment_solution_id assignment_solution_id CHAR(36) DEFAULT NULL, CHANGE evaluation_id evaluation_id CHAR(36) DEFAULT NULL, CHANGE submitted_by_id submitted_by_id CHAR(36) DEFAULT NULL, CHANGE submitted_at submitted_at DATETIME NOT NULL, CHANGE is_debug is_debug TINYINT NOT NULL, CHANGE failure_id failure_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE assignment_solver CHANGE id id CHAR(36) NOT NULL, CHANGE assignment_id assignment_id CHAR(36) DEFAULT NULL, CHANGE solver_id solver_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE async_job CHANGE id id CHAR(36) NOT NULL, CHANGE created_by_id created_by_id CHAR(36) DEFAULT NULL, CHANGE associated_assignment_id associated_assignment_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE comment CHANGE id id CHAR(36) NOT NULL, CHANGE user_id user_id CHAR(36) DEFAULT NULL, CHANGE is_private is_private TINYINT NOT NULL');
        $this->addSql('ALTER TABLE exercise CHANGE id id CHAR(36) NOT NULL, CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE exercise_config_id exercise_config_id CHAR(36) DEFAULT NULL, CHANGE is_public is_public TINYINT NOT NULL, CHANGE is_locked is_locked TINYINT NOT NULL, CHANGE is_broken is_broken TINYINT DEFAULT 0 NOT NULL, CHANGE score_config_id score_config_id CHAR(36) DEFAULT NULL, CHANGE merge_judge_logs merge_judge_logs TINYINT NOT NULL');
        $this->addSql('ALTER TABLE exercise_runtime_environment CHANGE exercise_id exercise_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_user CHANGE exercise_id exercise_id CHAR(36) NOT NULL, CHANGE user_id user_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_group CHANGE exercise_id exercise_id CHAR(36) NOT NULL, CHANGE group_id group_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_localized_exercise CHANGE exercise_id exercise_id CHAR(36) NOT NULL, CHANGE localized_exercise_id localized_exercise_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_hardware_group CHANGE exercise_id exercise_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_exercise_limits CHANGE exercise_id exercise_id CHAR(36) NOT NULL, CHANGE exercise_limits_id exercise_limits_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_exercise_environment_config CHANGE exercise_id exercise_id CHAR(36) NOT NULL, CHANGE exercise_environment_config_id exercise_environment_config_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_exercise_test CHANGE exercise_id exercise_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_exercise_file CHANGE exercise_id exercise_id CHAR(36) NOT NULL, CHANGE exercise_file_id exercise_file_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_attachment_file CHANGE exercise_id exercise_id CHAR(36) NOT NULL, CHANGE attachment_file_id attachment_file_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE exercise_config CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE exercise_environment_config CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE exercise_file_link CHANGE id id CHAR(36) NOT NULL, CHANGE exercise_file_id exercise_file_id CHAR(36) DEFAULT NULL, CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL, CHANGE assignment_id assignment_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE exercise_limits CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE exercise_score_config CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE exercise_tag CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE exercise_test CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE external_login CHANGE id id CHAR(36) NOT NULL, CHANGE user_id user_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE forgotten_password CHANGE id id CHAR(36) NOT NULL, CHANGE user_id user_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE `group` CHANGE id id CHAR(36) NOT NULL, CHANGE parent_group_id parent_group_id CHAR(36) DEFAULT NULL, CHANGE instance_id instance_id CHAR(36) DEFAULT NULL, CHANGE public_stats public_stats TINYINT NOT NULL, CHANGE is_public is_public TINYINT NOT NULL, CHANGE is_organizational is_organizational TINYINT DEFAULT 0 NOT NULL, CHANGE is_detaining is_detaining TINYINT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE group_exam CHANGE group_id group_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE group_exam_lock CHANGE student_id student_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE group_external_attribute CHANGE id id CHAR(36) NOT NULL, CHANGE group_id group_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE group_invitation CHANGE id id CHAR(36) NOT NULL, CHANGE group_id group_id CHAR(36) DEFAULT NULL, CHANGE host_id host_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE group_membership CHANGE id id CHAR(36) NOT NULL, CHANGE user_id user_id CHAR(36) DEFAULT NULL, CHANGE group_id group_id CHAR(36) DEFAULT NULL, CHANGE inherited_from_id inherited_from_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE instance CHANGE id id CHAR(36) NOT NULL, CHANGE admin_id admin_id CHAR(36) DEFAULT NULL, CHANGE root_group_id root_group_id CHAR(36) DEFAULT NULL, CHANGE is_open is_open TINYINT NOT NULL, CHANGE is_allowed is_allowed TINYINT NOT NULL, CHANGE needs_licence needs_licence TINYINT NOT NULL');
        $this->addSql('ALTER TABLE licence CHANGE id id CHAR(36) NOT NULL, CHANGE instance_id instance_id CHAR(36) DEFAULT NULL, CHANGE is_valid is_valid TINYINT NOT NULL');
        $this->addSql('ALTER TABLE localized_assignment CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE localized_exercise CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE localized_group CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL, CHANGE group_id group_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE localized_notification CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE localized_shadow_assignment CHANGE id id CHAR(36) NOT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE login CHANGE id id CHAR(36) NOT NULL, CHANGE user_id user_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE notification CHANGE id id CHAR(36) NOT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE visible_from visible_from DATETIME NOT NULL, CHANGE visible_to visible_to DATETIME NOT NULL');
        $this->addSql('ALTER TABLE notification_localized_notification CHANGE notification_id notification_id CHAR(36) NOT NULL, CHANGE localized_notification_id localized_notification_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE notification_group CHANGE notification_id notification_id CHAR(36) NOT NULL, CHANGE group_id group_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE pipeline CHANGE id id CHAR(36) NOT NULL, CHANGE pipeline_config_id pipeline_config_id CHAR(36) DEFAULT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE pipeline_exercise_file CHANGE pipeline_id pipeline_id CHAR(36) NOT NULL, CHANGE exercise_file_id exercise_file_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE pipeline_runtime_environment CHANGE pipeline_id pipeline_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE pipeline_config CHANGE id id CHAR(36) NOT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE pipeline_parameter CHANGE id id CHAR(36) NOT NULL, CHANGE pipeline_id pipeline_id CHAR(36) DEFAULT NULL, CHANGE boolean_value boolean_value TINYINT DEFAULT NULL');
        $this->addSql('ALTER TABLE plagiarism_detected_similar_file CHANGE id id CHAR(36) NOT NULL, CHANGE detected_similarity_id detected_similarity_id CHAR(36) DEFAULT NULL, CHANGE solution_id solution_id CHAR(36) DEFAULT NULL, CHANGE solution_file_id solution_file_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE plagiarism_detected_similarity CHANGE id id CHAR(36) NOT NULL, CHANGE batch_id batch_id CHAR(36) DEFAULT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE tested_solution_id tested_solution_id CHAR(36) DEFAULT NULL, CHANGE solution_file_id solution_file_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE plagiarism_detection_batch CHANGE id id CHAR(36) NOT NULL, CHANGE supervisor_id supervisor_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE reference_exercise_solution CHANGE id id CHAR(36) NOT NULL, CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL, CHANGE solution_id solution_id CHAR(36) DEFAULT NULL, CHANGE last_submission_id last_submission_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE reference_solution_submission CHANGE id id CHAR(36) NOT NULL, CHANGE reference_solution_id reference_solution_id CHAR(36) DEFAULT NULL, CHANGE evaluation_id evaluation_id CHAR(36) DEFAULT NULL, CHANGE submitted_by_id submitted_by_id CHAR(36) DEFAULT NULL, CHANGE submitted_at submitted_at DATETIME NOT NULL, CHANGE is_debug is_debug TINYINT NOT NULL, CHANGE failure_id failure_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE reported_errors CHANGE id id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE review_comment CHANGE id id CHAR(36) NOT NULL, CHANGE solution_id solution_id CHAR(36) DEFAULT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE security_event CHANGE user_id user_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE shadow_assignment CHANGE id id CHAR(36) NOT NULL, CHANGE group_id group_id CHAR(36) DEFAULT NULL, CHANGE is_public is_public TINYINT NOT NULL, CHANGE is_bonus is_bonus TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE shadow_assignment_localized_shadow_assignment CHANGE shadow_assignment_id shadow_assignment_id CHAR(36) NOT NULL, CHANGE localized_shadow_assignment_id localized_shadow_assignment_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE shadow_assignment_points CHANGE id id CHAR(36) NOT NULL, CHANGE shadow_assignment_id shadow_assignment_id CHAR(36) DEFAULT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE awardee_id awardee_id CHAR(36) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE awarded_at awarded_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE sis_group_binding CHANGE id id CHAR(36) NOT NULL, CHANGE group_id group_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE sis_valid_term CHANGE id id CHAR(36) NOT NULL, CHANGE beginning beginning DATETIME DEFAULT NULL, CHANGE end end DATETIME DEFAULT NULL, CHANGE advertise_until advertise_until DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE solution CHANGE id id CHAR(36) NOT NULL, CHANGE author_id author_id CHAR(36) DEFAULT NULL, CHANGE evaluated evaluated TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE solution_evaluation CHANGE id id CHAR(36) NOT NULL, CHANGE init_failed init_failed TINYINT NOT NULL, CHANGE score_config_id score_config_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE submission_failure CHANGE id id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE test_result CHANGE solution_evaluation_id solution_evaluation_id CHAR(36) DEFAULT NULL, CHANGE memory_exceeded memory_exceeded TINYINT NOT NULL, CHANGE wall_time_exceeded wall_time_exceeded TINYINT NOT NULL, CHANGE cpu_time_exceeded cpu_time_exceeded TINYINT NOT NULL');
        $this->addSql('ALTER TABLE uploaded_file CHANGE id id CHAR(36) NOT NULL, CHANGE user_id user_id CHAR(36) DEFAULT NULL, CHANGE solution_id solution_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE uploaded_partial_file CHANGE id id CHAR(36) NOT NULL, CHANGE user_id user_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE id id CHAR(36) NOT NULL, CHANGE settings_id settings_id CHAR(36) DEFAULT NULL, CHANGE is_verified is_verified TINYINT NOT NULL, CHANGE is_allowed is_allowed TINYINT NOT NULL, CHANGE token_validity_threshold token_validity_threshold DATETIME DEFAULT NULL, CHANGE last_authentication_at last_authentication_at DATETIME DEFAULT NULL, CHANGE ui_data_id ui_data_id CHAR(36) DEFAULT NULL, CHANGE group_lock_id group_lock_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE user_instance CHANGE user_id user_id CHAR(36) NOT NULL, CHANGE instance_id instance_id CHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE user_calendar CHANGE user_id user_id CHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE user_settings CHANGE id id CHAR(36) NOT NULL, CHANGE new_assignment_emails new_assignment_emails TINYINT NOT NULL, CHANGE assignment_deadline_emails assignment_deadline_emails TINYINT NOT NULL, CHANGE submission_evaluated_emails submission_evaluated_emails TINYINT NOT NULL, CHANGE solution_comments_emails solution_comments_emails TINYINT NOT NULL, CHANGE points_changed_emails points_changed_emails TINYINT NOT NULL, CHANGE assignment_submit_after_accepted_emails assignment_submit_after_accepted_emails TINYINT NOT NULL, CHANGE assignment_submit_after_reviewed_emails assignment_submit_after_reviewed_emails TINYINT NOT NULL, CHANGE assignment_comments_emails assignment_comments_emails TINYINT NOT NULL');
        $this->addSql('ALTER TABLE user_ui_data CHANGE id id CHAR(36) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assignment CHANGE is_public is_public TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_bonus is_bonus TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE visible_from visible_from DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE allow_second_deadline allow_second_deadline TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE can_view_limit_ratios can_view_limit_ratios TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE can_view_judge_stdout can_view_judge_stdout TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE can_view_judge_stderr can_view_judge_stderr TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE merge_judge_logs merge_judge_logs TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE plagiarism_batch_id plagiarism_batch_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_config_id exercise_config_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE score_config_id score_config_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_attachment_file CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE attachment_file_id attachment_file_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_disabled_runtime_environments CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_exercise_environment_config CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_environment_config_id exercise_environment_config_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_exercise_file CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_file_id exercise_file_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_exercise_limits CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_limits_id exercise_limits_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_exercise_test CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_hardware_group CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_localized_assignment CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE localized_assignment_id localized_assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_localized_exercise CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE localized_exercise_id localized_exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_runtime_environment CHANGE assignment_id assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_solution CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE accepted accepted TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE assignment_id assignment_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE solution_id solution_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE last_submission_id last_submission_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE plagiarism_batch_id plagiarism_batch_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_solution_submission CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE submitted_at submitted_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE is_debug is_debug TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE submitted_by_id submitted_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE evaluation_id evaluation_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE assignment_solution_id assignment_solution_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE failure_id failure_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE assignment_solver CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE assignment_id assignment_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE solver_id solver_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE async_job CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_by_id created_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE associated_assignment_id associated_assignment_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE comment CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE is_private is_private TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE is_public is_public TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_locked is_locked TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_broken is_broken TINYINT DEFAULT 0 NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE merge_judge_logs merge_judge_logs TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_config_id exercise_config_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE score_config_id score_config_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_attachment_file CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE attachment_file_id attachment_file_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_config CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_environment_config CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_exercise_environment_config CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_environment_config_id exercise_environment_config_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_exercise_file CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_file_id exercise_file_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_exercise_limits CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_limits_id exercise_limits_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_exercise_test CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_file_link CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_file_id exercise_file_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE assignment_id assignment_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_group CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_hardware_group CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_limits CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_localized_exercise CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE localized_exercise_id localized_exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_runtime_environment CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_score_config CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_tag CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_test CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_user CHANGE exercise_id exercise_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE user_id user_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE external_login CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE forgotten_password CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE `group` CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE public_stats public_stats TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_public is_public TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_organizational is_organizational TINYINT DEFAULT 0 NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_detaining is_detaining TINYINT DEFAULT 0 NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE parent_group_id parent_group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE instance_id instance_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE group_exam CHANGE group_id group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE group_exam_lock CHANGE student_id student_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE group_external_attribute CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE group_invitation CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE host_id host_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE group_membership CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE inherited_from_id inherited_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE instance CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE is_open is_open TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_allowed is_allowed TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE needs_licence needs_licence TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE admin_id admin_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE root_group_id root_group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE licence CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE is_valid is_valid TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE instance_id instance_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE localized_assignment CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE localized_exercise CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE localized_group CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE localized_notification CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE localized_shadow_assignment CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE login CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE notification CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE visible_from visible_from DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE visible_to visible_to DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE notification_group CHANGE notification_id notification_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE notification_localized_notification CHANGE notification_id notification_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE localized_notification_id localized_notification_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE pipeline CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE pipeline_config_id pipeline_config_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE pipeline_config CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE created_from_id created_from_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE pipeline_exercise_file CHANGE pipeline_id pipeline_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_file_id exercise_file_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE pipeline_parameter CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE pipeline_id pipeline_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE boolean_value boolean_value TINYINT DEFAULT NULL COMMENT \'(DC2Type:boolean)\'');
        $this->addSql('ALTER TABLE pipeline_runtime_environment CHANGE pipeline_id pipeline_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE plagiarism_detected_similarity CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE batch_id batch_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE tested_solution_id tested_solution_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE solution_file_id solution_file_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE plagiarism_detected_similar_file CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE detected_similarity_id detected_similarity_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE solution_id solution_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE solution_file_id solution_file_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE plagiarism_detection_batch CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE supervisor_id supervisor_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE reference_exercise_solution CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE exercise_id exercise_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE solution_id solution_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE last_submission_id last_submission_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE reference_solution_submission CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE submitted_at submitted_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE is_debug is_debug TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE submitted_by_id submitted_by_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE evaluation_id evaluation_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE reference_solution_id reference_solution_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE failure_id failure_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE reported_errors CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE review_comment CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE solution_id solution_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE security_event CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE shadow_assignment CHANGE is_public is_public TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_bonus is_bonus TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE deleted_at deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE shadow_assignment_localized_shadow_assignment CHANGE shadow_assignment_id shadow_assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE localized_shadow_assignment_id localized_shadow_assignment_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE shadow_assignment_points CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE awarded_at awarded_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE shadow_assignment_id shadow_assignment_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE awardee_id awardee_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE sis_group_binding CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_id group_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE sis_valid_term CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE beginning beginning DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE end end DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE advertise_until advertise_until DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE solution CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE evaluated evaluated TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', CHANGE author_id author_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE solution_evaluation CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE init_failed init_failed TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE score_config_id score_config_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE submission_failure CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE test_result CHANGE memory_exceeded memory_exceeded TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE wall_time_exceeded wall_time_exceeded TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE cpu_time_exceeded cpu_time_exceeded TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE solution_evaluation_id solution_evaluation_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE `uploaded_file` CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE solution_id solution_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE uploaded_partial_file CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE user CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE is_verified is_verified TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE is_allowed is_allowed TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE token_validity_threshold token_validity_threshold DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE last_authentication_at last_authentication_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', CHANGE settings_id settings_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE ui_data_id ui_data_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE group_lock_id group_lock_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE user_calendar CHANGE user_id user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE user_instance CHANGE user_id user_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE instance_id instance_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE user_settings CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE new_assignment_emails new_assignment_emails TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE assignment_deadline_emails assignment_deadline_emails TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE submission_evaluated_emails submission_evaluated_emails TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE solution_comments_emails solution_comments_emails TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE assignment_comments_emails assignment_comments_emails TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE points_changed_emails points_changed_emails TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE assignment_submit_after_accepted_emails assignment_submit_after_accepted_emails TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\', CHANGE assignment_submit_after_reviewed_emails assignment_submit_after_reviewed_emails TINYINT NOT NULL COMMENT \'(DC2Type:boolean)\'');
        $this->addSql('ALTER TABLE user_ui_data CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\'');
    }
}
