<?php

namespace App\Console;

use App\Helpers\Notifications\ReviewsEmailsSender;
use App\Model\Repository\AssignmentSolutions;
use App\Model\Entity\Group;
use App\Model\Entity\User;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use DateTime;

class GenerateSwagger extends Command
{
    protected static $defaultName = 'swagger:generate';

    protected function configure()
    {
        $this->setName(self::$defaultName)->setDescription(
            'Generate a swagger specification file from existing code.'
        );
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $path = __DIR__ . '/../V1Module/presenters/_autogenerated_annotations_temp.php';
        $openapi = \OpenApi\Generator::scan([$path]);

        header('Content-Type: application/x-yaml');
        $output->writeln($openapi->toYaml());

        # delete the temp file
        unlink($path);

        return Command::SUCCESS;
    }
}
