<?php

namespace App\Helpers\Swagger;

/**
 * Builder class that handles annotation .php file creation.
 */
class TempAnnotationFileBuilder
{
    private $methodEntries;
    private string $content;
    private string $filename;

    public function __construct(
        string $filename
    ) {
        $this->content = "";
        $this->methodEntries = 0;
        $this->filename = $filename;
        $this->initFile();
    }

    private function initFile()
    {
        $this->content .= "<?php\n";
        $this->content .= "/// THIS FILE WAS AUTOGENERATED\n";
        $this->content .= "namespace App\V1Module\Presenters;\n";
        $this->content .= "use OpenApi\Annotations as OA;\n";
    }

    private function createInfoAnnotation(string $version, string $title)
    {
        $head = "@OA\\Info";
        $body = new ParenthesesBuilder();
        $body->addKeyValue("version", $version);
        $body->addKeyValue("title", $title);
        return $head . $body->toString();
    }

    private function writeAnnotationLineWithComments(string $annotationLine)
    {
        $this->content .= "/**\n";
        $this->content .= "* {$annotationLine}\n";
        $this->content .= "*/\n";
    }

    public function startClass(string $className, string $version, string $title)
    {
        $this->writeAnnotationLineWithComments($this->createInfoAnnotation($version, $title));
        $this->content .= "class {$className} {\n";
    }

    /**
     * Ends the class and writes the contents to the disk.
     */
    public function endClass()
    {
        $this->content .= "}\n";
        $this->close();
    }

    public function addAnnotatedMethod(string $methodName, string $annotationLine)
    {
        $this->writeAnnotationLineWithComments($annotationLine);
        $this->content .= "public function {$methodName}{$this->methodEntries}() {}\n";
        $this->methodEntries++;
    }

    public function close()
    {
        $file = fopen($this->filename, "w");
        fwrite($file, $this->content);
        fflush($file);
        fclose($file);
    }
}
