name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with pecl and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: pecl,composer:v2
        coverage: xdebug
        extensions: yaml,tokenizer,ldap,pdo,pdo_sqlite,zip,json,mbstring,iconv,zmq
        ini-values: memory_limit=1G,opcache.enable_cli=0
    - run: php --version
        
    # install
    - run: composer install --no-interaction --prefer-dist
    
    # script
    - run: php ./vendor/nette/tester/src/tester.php -j 4 -C tests --coverage ./coverage.xml --coverage-src ./app
    - uses: codecov/codecov-action@v1
    
  phpstan:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with pecl and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: pecl,composer:v2
        extensions: yaml,tokenizer,ldap,pdo,pdo_sqlite,zip,json,mbstring,iconv,zmq
        ini-values: memory_limit=1G,opcache.enable_cli=0
    - run: php --version
    
    # install
    - run: composer install --no-interaction --prefer-dist
    
    # script
    - run: vendor/bin/phpstan analyse -c phpstan/phpstan.neon app

  phpstan-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with pecl and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl,composer:v2
          extensions: yaml,tokenizer,ldap,pdo,pdo_sqlite,zip,json,mbstring,iconv,zmq
          ini-values: memory_limit=1G,opcache.enable_cli=0
      - run: php --version

      # install
      - run: composer install --no-interaction --prefer-dist

      # script
      - run: vendor/bin/phpstan analyse -c phpstan/phpstan.neon tests
